services:
  app:
    image: flight-diary-app
    build:
      context: ./frontend 
      dockerfile: Dockerfile 
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5173:5173"
    container_name: flight-diary-app

  server:
    image: flight-diary-backend
    build:
      context: ./backend 
      dockerfile: Dockerfile 
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules 
    ports:
      - "3000:3000"
    container_name: flight-diary-backend

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app
      - server